### ISSUE TITLE
    get_eventId_NextEvent(self)

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/ChurchToolsAPI#3]
Aus https://forum.songbeamer.de/viewtopic.php?f=1&p=23001&sid=d7f00735d9dccdcc0eb7ba89baa0e489#p23001
Implementierung von [kolibri52](https://forum.songbeamer.de/memberlist.php?mode=viewprofile&u=2046) aber noch nicht geteilt.

**Comment by bensteUEM** [comment]
Vorschlag -> get_events(next:true) für einheiltiche Struktur

**Comment by kolibri52** [comment]
Okay - the actual existing function is defined as  get_events(self, event_id=None).
Shall I change it to  get_events(self, event=next)
whereas the "event" parameter accepts:
- numeric event id (returns one specific event -> as it is actually)
- none (returns all events -> as it is actually)
- next (returns only the next event -> new feature)

In my opinion 'next' would be a good default-value.

**Comment by bensteUEM** [comment]
I would suggest keeping the existing optional "event_id" param and add a new optional "limit" param which limits the the number of results, in addition to a new optional "sort" param which default to ID but can be changed to event_date 

This would enable the use of one multi puprose function and if used with limit=1 and sort="event_date" implement the requested "next event" functionality

**Comment by bensteUEM** [comment]
i had a look at the original API again ... there was also an existing bug report which relates to this ...
please see https://elkw1610.krz.tools/api/ Events endpoint for the params to use

Best would be to implement the same params as with the API ...
*  from
* to 
* canceled
* direction
* limit

i would suggest marking this issue as duplicate of #2  ? Feel free to solve it ...

**Comment by bensteUEM** [comment]
closed as duplicate of #2
