### ISSUE TITLE
Implement update_group()

### ISSUE THREAD

**Issue by fschrempf** [bensteUEM/ChurchToolsAPI#75]
- [x] Create isolated commit
- [x] Draft test case
- [x] Adjust test case to demo system

**Comment by bensteUEM** [comment]
@fschrempf  - FYI i will change from keyword id to param group_id for consistency
+ i do get an error when executing the test - but will investigate ist

`{'message': 'There are validation errors', 'messageKey': 'validation.error', 'translatedMessage': 'Die eingegebenen Daten waren nicht korrekt.', 'args': [], 'errors': [{...}]}`

**Comment by bensteUEM** [comment]
Scheint aber ein permission error zu sein...```

{
    "message": "Forbidden to edit the field note",
    "translatedMessage": "Keine Berechtigung, das Feld note zu sehen oder zu bearbeiten",
    "messageKey": "error.forbidden.edit.field",
    "args": {
        "field": "note"
    },
    "errors": []
```
